# /// script
# requires-python = ">=3.10"
# dependencies = [
#   "pypdf>=4.0",
#   "reportlab>=4.0",
# ]
# ///
"""
tests/p2_chunk.py -- Phase P2 acceptance test.

Plain Python script; no pytest.  Prints what it checks; exits 0 on full
pass, non-zero if any assertion fails.

Tests the paragraph-aware chunk_text(): ~1500-char chunks + 1-para overlap,
blank-line paragraph boundaries, sentence-split for oversized paragraphs.

Run with:
    bin\\uv.exe run tests\\p2_chunk.py          (from the project root on Windows)
    bin/uv run tests/p2_chunk.py               (macOS / Linux)
"""

from __future__ import annotations

import io
import os
import sys
import traceback
from pathlib import Path

# ---------------------------------------------------------------------------
# Locate the project root and add it to sys.path so we can import ingest_lib
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

import ingest_lib  # noqa: E402


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

PASS = "PASS"
FAIL = "FAIL"
_results: list[tuple[str, str]] = []


def check(name: str, condition: bool, detail: str = "") -> bool:
    status = PASS if condition else FAIL
    msg = f"  [{status}] {name}"
    if detail:
        msg += f" -- {detail}"
    print(msg)
    _results.append((name, status))
    return condition


def section(title: str) -> None:
    print(f"\n{'='*60}")
    print(f"  {title}")
    print("=" * 60)


# ---------------------------------------------------------------------------
# Known sentences placed deliberately in the sample files.
#
# With the paragraph-aware ~1500-char chunker, sample.txt's first chunk
# covers the opening paragraphs including the CAP theorem paragraph, so
# the known sentence lands in chunk 0.
#
# sample.md: K-means paragraph follows multiple supervised-learning paragraphs
# that together exceed 1500 chars, so K-means lands in chunk 1.
# ---------------------------------------------------------------------------
KNOWN_TXT_SENTENCE = (
    "The CAP theorem, formulated by Eric Brewer in 2000, states that a "
    "distributed system cannot simultaneously provide all three"
)
KNOWN_TXT_CHUNK = 0  # expected 0-based chunk index (paragraph-aware chunker)

KNOWN_MD_SENTENCE = (
    "K-means clustering partitions data into k clusters by iteratively"
)
KNOWN_MD_CHUNK = 1  # expected 0-based chunk index (paragraph-aware chunker)

# Paragraph-aware chunker target (chars).  Single source of truth lives in
# ingest_lib; the test references it so changing the knob never breaks this test.
# Chunks may vary somewhat with paragraph boundaries; we check the target is
# roughly met.
TARGET_CHARS = ingest_lib.DEFAULT_TARGET_CHARS
# Paragraph-aware chunks may be smaller when approaching document end;
# only check that chunks at least 2 before the last are >= 50% of target.
# This avoids false failures on short trailing paragraphs.
TOLERANCE = 0.50   # chunks (excluding last 2) should be >= 50% of target_chars

# Minimum overlap in chars between consecutive chunks (1-para overlap).
# One paragraph in sample.txt is typically 300-800 chars.
MIN_OVERLAP_CHARS = 50


# ---------------------------------------------------------------------------
# PDF generation (via reportlab) -- create a tiny valid PDF in a temp file
# ---------------------------------------------------------------------------

def make_test_pdf(dest: Path) -> str:
    """
    Write a minimal PDF with a known sentence and return that sentence.
    Uses reportlab (declared in this script's inline deps).
    """
    from reportlab.lib.pagesizes import LETTER  # type: ignore[import-untyped]
    from reportlab.pdfgen import canvas  # type: ignore[import-untyped]

    known = "The PDF extraction sentinel: distributed systems use replication."

    c = canvas.Canvas(str(dest), pagesize=LETTER)
    width, height = LETTER
    text_obj = c.beginText(72, height - 72)
    text_obj.setFont("Helvetica", 12)
    text_obj.textLine("Test PDF document for slm-rag P2.")
    text_obj.textLine("")
    text_obj.textLine(known)
    text_obj.textLine("")
    text_obj.textLine(
        "This document is auto-generated by tests/p2_chunk.py to verify "
        "that extract_text correctly reads PDF files via pypdf."
    )
    c.drawText(text_obj)
    c.save()
    return known


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

def test_txt(samples_dir: Path) -> None:
    section("TXT sample -- ingest_file + paragraph-aware chunk assertions")
    path = samples_dir / "sample.txt"

    check("sample.txt exists", path.exists(), str(path))
    if not path.exists():
        return

    chunks = ingest_lib.ingest_file(path)
    raw = ingest_lib.extract_text(path)
    n = len(chunks)
    check("multiple chunks produced", n > 1, f"got {n} chunks")

    # --- chunk sizes: all but last 2 must be >= 50% of target_chars ---
    # Paragraph-aware chunks may be small near the document end; only check
    # chunks well before the end to avoid spurious failures.
    low = int(TARGET_CHARS * TOLERANCE)
    bad_sizes = []
    for c in chunks[:-2]:
        clen = c["char_end"] - c["char_start"]
        if clen < low:
            bad_sizes.append((c["chunk_index"], clen))
    check(
        f"chunks (excl. last 2) are >= {low} chars ({int(TOLERANCE*100)}% of target)",
        len(bad_sizes) == 0,
        f"bad: {bad_sizes}" if bad_sizes else f"all >= {low} chars",
    )

    # --- char_start / char_end monotonic and in-range ---
    rlen = len(raw)
    mono_ok = True
    inrange_ok = True
    for c in chunks:
        if not (0 <= c["char_start"] < c["char_end"] <= rlen):
            inrange_ok = False
        if c["char_start"] >= c["char_end"]:
            mono_ok = False
    for i in range(len(chunks) - 1):
        if chunks[i]["char_start"] >= chunks[i + 1]["char_start"]:
            mono_ok = False
    check("char offsets are in-range [0, len(text)]", inrange_ok)
    check("char_start values are strictly increasing", mono_ok)

    # --- roundtrip: text[char_start:char_end] == chunk['text'] ---
    bad_rt = []
    for c in chunks:
        recovered = raw[c["char_start"]: c["char_end"]]
        if recovered != c["text"]:
            bad_rt.append(c["chunk_index"])
    check(
        "text[char_start:char_end] recovers chunk text exactly",
        len(bad_rt) == 0,
        f"bad chunks: {bad_rt}" if bad_rt else "all chunks round-trip",
    )

    # --- overlap: consecutive chunks share text (1-para overlap) ---
    bad_overlaps = []
    for i in range(len(chunks) - 1):
        a, b = chunks[i], chunks[i + 1]
        overlap_chars = max(0, a["char_end"] - b["char_start"])
        if overlap_chars < MIN_OVERLAP_CHARS:
            bad_overlaps.append((i, overlap_chars))
    check(
        f"consecutive chunks overlap by >= {MIN_OVERLAP_CHARS} chars (1-para overlap)",
        len(bad_overlaps) == 0,
        f"bad pairs: {bad_overlaps}" if bad_overlaps
        else f"all overlaps >= {MIN_OVERLAP_CHARS} chars",
    )

    # --- source_path set ---
    all_have_src = all("source_path" in c for c in chunks)
    check("source_path present on all chunks", all_have_src)

    # --- known sentence in expected chunk with correct offsets ---
    containing = [c for c in chunks if KNOWN_TXT_SENTENCE in c["text"]]
    found = len(containing) > 0
    check(
        f"known sentence found in chunks (expected chunk ~{KNOWN_TXT_CHUNK})",
        found,
        f"found in chunk(s) {[c['chunk_index'] for c in containing]}"
        if found else "NOT FOUND",
    )
    if found:
        c0 = containing[0]
        # Verify offsets slice back to the sentence
        idx_in_chunk = c0["text"].find(KNOWN_TXT_SENTENCE)
        abs_start = c0["char_start"] + idx_in_chunk
        recovered = raw[abs_start: abs_start + len(KNOWN_TXT_SENTENCE)]
        check(
            "known sentence offsets slice back correctly from original text",
            recovered == KNOWN_TXT_SENTENCE,
            repr(recovered[:60]),
        )


def test_md(samples_dir: Path) -> None:
    section("MD sample -- ingest_file + paragraph-aware chunk assertions")
    path = samples_dir / "sample.md"

    check("sample.md exists", path.exists(), str(path))
    if not path.exists():
        return

    chunks = ingest_lib.ingest_file(path)
    n = len(chunks)
    check("multiple chunks produced", n > 1, f"got {n} chunks")

    raw = ingest_lib.extract_text(path)
    rlen = len(raw)

    # --- chunk sizes: all but last 2 must be >= 50% of target_chars ---
    low = int(TARGET_CHARS * TOLERANCE)
    bad_sizes = []
    for c in chunks[:-2]:
        clen = c["char_end"] - c["char_start"]
        if clen < low:
            bad_sizes.append((c["chunk_index"], clen))
    check(
        f"chunks (excl. last 2) are >= {low} chars ({int(TOLERANCE*100)}% of target)",
        len(bad_sizes) == 0,
        f"bad: {bad_sizes}" if bad_sizes else "all within tolerance",
    )

    # --- char offsets in-range and monotonic ---
    mono_ok = True
    inrange_ok = True
    for c in chunks:
        if not (0 <= c["char_start"] < c["char_end"] <= rlen):
            inrange_ok = False
    for i in range(len(chunks) - 1):
        if chunks[i]["char_start"] >= chunks[i + 1]["char_start"]:
            mono_ok = False
    check("char offsets are in-range", inrange_ok)
    check("char_start values are strictly increasing", mono_ok)

    # --- roundtrip ---
    bad_rt = [c["chunk_index"] for c in chunks if raw[c["char_start"]:c["char_end"]] != c["text"]]
    check("text[char_start:char_end] recovers chunk text exactly", len(bad_rt) == 0,
          f"bad: {bad_rt}" if bad_rt else "all round-trip")

    # --- overlap ---
    bad_overlaps = []
    for i in range(len(chunks) - 1):
        a, b = chunks[i], chunks[i + 1]
        overlap_chars = max(0, a["char_end"] - b["char_start"])
        if overlap_chars < MIN_OVERLAP_CHARS:
            bad_overlaps.append((i, overlap_chars))
    check(
        f"consecutive chunks overlap by >= {MIN_OVERLAP_CHARS} chars",
        len(bad_overlaps) == 0,
        f"bad pairs: {bad_overlaps}" if bad_overlaps else "all overlaps OK",
    )

    # --- known sentence ---
    containing = [c for c in chunks if KNOWN_MD_SENTENCE in c["text"]]
    found = len(containing) > 0
    check(
        f"known sentence found in chunks (expected chunk ~{KNOWN_MD_CHUNK})",
        found,
        f"found in chunk(s) {[c['chunk_index'] for c in containing]}"
        if found else "NOT FOUND",
    )
    if found:
        c0 = containing[0]
        idx_in_chunk = c0["text"].find(KNOWN_MD_SENTENCE)
        abs_start = c0["char_start"] + idx_in_chunk
        recovered = raw[abs_start: abs_start + len(KNOWN_MD_SENTENCE)]
        check(
            "known sentence offsets slice back correctly",
            recovered == KNOWN_MD_SENTENCE,
            repr(recovered[:60]),
        )


def test_pdf(tmp_dir: Path) -> None:
    section("PDF sample -- extract_text dispatch + content check")

    pdf_path = tmp_dir / "test_gen.pdf"
    try:
        known_sentence = make_test_pdf(pdf_path)
        generated = True
    except Exception as exc:
        print(f"  [INFO] reportlab PDF generation failed ({exc}); "
              "falling back to dispatch-only test.")
        generated = False

    if generated:
        check("generated PDF exists", pdf_path.exists())
        try:
            text = ingest_lib.extract_text(pdf_path)
            check("extract_text returns non-empty string for PDF", len(text) > 0,
                  f"{len(text)} chars")
            check(
                "known sentence present in extracted PDF text",
                known_sentence in text,
                repr(text[:120]),
            )
        except Exception as exc:
            check("extract_text on PDF did not raise", False, str(exc))
    else:
        check(
            "PDF dispatch test skipped (reportlab unavailable)",
            True,
            "PDF extraction path is exercised in generated-PDF branch when reportlab is present",
        )


def test_unsupported_extension() -> None:
    section("Unsupported extension -- expect ValueError")
    try:
        ingest_lib.extract_text("some_file.docx")
        check("ValueError raised for .docx", False, "no exception raised")
    except ValueError as exc:
        check("ValueError raised for .docx", True, str(exc))
    except FileNotFoundError:
        check("error raised for .docx (FileNotFoundError also acceptable)", True,
              "FileNotFoundError -- file not found before type check")
    except Exception as exc:
        check("ValueError raised for .docx", False, f"wrong exception: {exc}")


def test_chunk_text_unit() -> None:
    """Unit tests for chunk_text() directly, independent of file I/O.

    Tests the paragraph-aware chunker (target_chars=1500, overlap_paras=1).
    """
    section("chunk_text() unit tests -- paragraph-aware chunker")

    # ------------------------------------------------------------------ #
    # Test 1: multi-paragraph text produces multiple chunks + roundtrip   #
    # ------------------------------------------------------------------ #
    # Build text with ~10 paragraphs each ~350 chars (~3500 chars/para x 10).
    # With target_chars=1500 we expect a handful of chunks on 10 paras.
    paras = []
    for i in range(10):
        # Each paragraph is ~350 chars.
        paras.append(
            f"Paragraph {i}: " + " ".join(f"word{j:04d}" for j in range(50))
        )
    text = "\n\n".join(paras)

    chunks = ingest_lib.chunk_text(text)   # exercise the real defaults
    check("unit: multiple chunks for 10 paragraphs", len(chunks) > 1, f"got {len(chunks)}")

    # All char offsets should recover the chunk text.
    bad_rt = [c["chunk_index"] for c in chunks if text[c["char_start"]:c["char_end"]] != c["text"]]
    check("unit: all chunks round-trip via char offsets", len(bad_rt) == 0,
          f"bad: {bad_rt}" if bad_rt else "ok")

    # Overlap: consecutive chunks should overlap (1-para overlap).
    bad_ovlp = []
    for i in range(len(chunks) - 1):
        a, b = chunks[i], chunks[i + 1]
        overlap_chars = max(0, a["char_end"] - b["char_start"])
        if overlap_chars < MIN_OVERLAP_CHARS:
            bad_ovlp.append((i, overlap_chars))
    check("unit: consecutive chunks overlap (1-para overlap)", len(bad_ovlp) == 0,
          f"bad: {bad_ovlp}" if bad_ovlp else "ok")

    # char_start strictly increasing
    mono_ok = all(chunks[i]["char_start"] < chunks[i+1]["char_start"]
                  for i in range(len(chunks)-1))
    check("unit: char_start strictly increasing", mono_ok)

    # ------------------------------------------------------------------ #
    # Test 2: empty / whitespace-only text                                #
    # ------------------------------------------------------------------ #
    empty = ingest_lib.chunk_text("")
    check("unit: empty text returns []", empty == [], f"got {empty}")

    ws = ingest_lib.chunk_text("   \n\t  ")
    check("unit: whitespace-only text returns []", ws == [], f"got {ws}")

    # ------------------------------------------------------------------ #
    # Test 3: single paragraph below target -> 1 chunk                   #
    # ------------------------------------------------------------------ #
    single_para = "Hello world. This is a short paragraph."
    sp_chunks = ingest_lib.chunk_text(single_para)
    check("unit: single short paragraph returns 1 chunk",
          len(sp_chunks) == 1, f"got {len(sp_chunks)}")
    if sp_chunks:
        rt = single_para[sp_chunks[0]["char_start"]:sp_chunks[0]["char_end"]]
        check("unit: single chunk round-trips", rt == sp_chunks[0]["text"],
              repr(rt[:60]))

    # ------------------------------------------------------------------ #
    # Test 4: a known sentence lands in a chunk (and offsets are correct) #
    # ------------------------------------------------------------------ #
    MARKER = "The vampire asked the detective about the missing medallion."
    doc = (
        "Introduction paragraph with some filler text to pad it out.\n\n"
        "Second paragraph, more filler text here to ensure we have enough words.\n\n"
        f"{MARKER}  The detective replied that it had last been seen in Budapest.\n\n"
        "Fourth paragraph wrapping up the story with a satisfying conclusion."
    )
    dc = ingest_lib.chunk_text(doc, target_chars=200, overlap_paras=1)
    found = [c for c in dc if MARKER in c["text"]]
    check("unit: known sentence lands in a chunk", len(found) > 0,
          f"found in {[c['chunk_index'] for c in found]}" if found else "NOT FOUND")
    if found:
        c0 = found[0]
        idx = c0["text"].find(MARKER)
        abs_start = c0["char_start"] + idx
        recovered = doc[abs_start: abs_start + len(MARKER)]
        check("unit: known sentence offsets slice back from original",
              recovered == MARKER, repr(recovered[:60]))

    # ------------------------------------------------------------------ #
    # Test 5: oversized single paragraph gets sentence-split              #
    # ------------------------------------------------------------------ #
    # Build a single paragraph > 1.5 * 200 = 300 chars with many sentences.
    sentences = [f"Sentence number {k} ends here." for k in range(30)]
    big_para = "  ".join(sentences)   # ~900 chars, no blank lines
    bp_chunks = ingest_lib.chunk_text(big_para, target_chars=200, overlap_paras=1)
    check("unit: oversized single paragraph is split into multiple chunks",
          len(bp_chunks) > 1, f"got {len(bp_chunks)}")
    bad_rt2 = [c["chunk_index"] for c in bp_chunks
               if big_para[c["char_start"]:c["char_end"]] != c["text"]]
    check("unit: sentence-split chunks round-trip", len(bad_rt2) == 0,
          f"bad: {bad_rt2}" if bad_rt2 else "ok")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    samples_dir = PROJECT_ROOT / "samples"
    tmp_dir = PROJECT_ROOT / "samples"  # reuse samples dir for temp PDF

    print("=" * 60)
    print("  slm-rag P2 -- text extraction + chunking tests")
    print("  (paragraph-aware chunker, ~1500 chars + 1-para overlap)")
    print("=" * 60)

    test_txt(samples_dir)
    test_md(samples_dir)
    test_pdf(tmp_dir)
    test_unsupported_extension()
    test_chunk_text_unit()

    # Summary
    print(f"\n{'='*60}")
    passed = sum(1 for _, s in _results if s == PASS)
    failed = sum(1 for _, s in _results if s == FAIL)
    print(f"  Results: {passed} passed, {failed} failed  ({len(_results)} checks)")
    print("=" * 60)

    if failed > 0:
        print("\nFAILED checks:")
        for name, status in _results:
            if status == FAIL:
                print(f"  - {name}")
        return 1

    print("\nAll checks PASSED.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
